# Generated by Django 5.1.3 on 2024-11-22 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='content',
            table=None,
        ),
    ]
