# Generated by Django 5.1.3 on 2024-11-22 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='created_at',
        ),
    ]
