# Generated by Django 5.1.3 on 2025-01-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_course_description_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=9),
        ),
    ]
