# Generated by Django 5.1.3 on 2024-11-22 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_progress_unique_together_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.courses')),
            ],
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
    ]
