# Generated by Django 5.1.3 on 2025-01-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_lesson_description_alter_lesson_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
    ]
