# Generated by Django 5.1.3 on 2025-01-16 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_course_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresource',
            name='file',
            field=models.FileField(upload_to='lesson_resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'docx', 'pptx'])]),
        ),
    ]
