# Generated by Django 5.1.3 on 2025-01-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_lessonresource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresource',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
