# Generated by Django 5.1.3 on 2024-12-16 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_lessonresources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresources',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'jpg', 'jpeg', 'png', 'docx', 'pptx', 'xlsx'])]),
        ),
    ]
